### ISSUE TITLE
Neighbors error with SB, due to game change

### ISSUE THREAD

**Issue by ziphmose** [TheRealGangsir/Subterrain#2]
attempted to place an underground belt and received this message followed by the game kicking me back to the main menu:

Error while running event Subterrain::on_built_entity (ID 6)
__Subterrain__/control.lua:43: attempt to index field 'neighbours' (a nil value)

**Comment by Sublimelime** [comment]
@ziphmose Thanks for the report, working on a fix.

**Comment by Helixander** [comment]
I removed the [1] value from lines 43 and 44. So far, seems to be working as intended.

**Comment by Cornyne** [comment]
Had this error when Removing a placed section, error listed next line.

4440.019 Error MainLoop.cpp:850: Exception at tick 21242376: Error while running event Subterrain::on_preplayer_mined_item (ID 11)
LuaEntity doesn't contain key 1.
stack traceback:
	__Subterrain__/control.lua:124: in function <__Subterrain__/control.lua:114>

Thanks for the Mod

**Comment by Helixander** [comment]
Remove the nil value [1] from lines 43, 44, and 124 removes these errors.

**Comment by Sublimelime** [comment]
Thanks. I'll put out an official fix soon. Thanks to @Cornyne and @Helixander for the info.
